version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=epigraphsBDD
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ~/data:/var/lib/postgresql/data
    command: postgres -D /var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
